### ISSUE TITLE
prepare_agent job does not update linode_agent_list

### ISSUE THREAD

**Issue by bengland2** [acalhounRH/automated_ceph_test#1]
it updates agent_list, but the 1A-Retreive_RHCS_ISO_for_Linode job does not read that, it reads linode_agent_list.  Why have 2 agent lists?  Just have 1 and then you can tell if it's a linode agent because it will have linode.com in the FQDN (fully qualified DNS domain name)

**Comment by acalhounRH** [comment]
Just forgot the retreive job also uses this file. will update.
