### ISSUE TITLE
wildcards for .iso file don't work

### ISSUE THREAD

**Issue by bengland2** [acalhounRH/automated_ceph_test#29]
For reasons I can't explain, in 1-Deploy_Ceph_Cluster.sh,  wildcard like RHCEPH-*-x86_64-dvd.iso does not work for the ISO image name, but if you put in a non-wildcard name it works :-(  Would really like the wildcard to work as it saves time - you only have to specify the URL for the directory containing the ISO image then (and the version_adjust_repo and ansible_version)

**Comment by acalhounRH** [comment]
No longer seeing issue occur after implimentation of 1A-Push_SW_To_Remote_Agent.sh
