### ISSUE TITLE
Prepare_Agent trying to install RH-internal git repo from linode.com

### ISSUE THREAD

**Issue by bengland2** [acalhounRH/automated_ceph_test#3]
the script tries to clone a redhat-internal git repo and can't do it.

The reason for this is that the bash script doesn't exit if a yum command fails, it just keeps on going.

In this case, that might have been the right outcome, because we probably don't need perf-dept repo unless you are on RH-internal servers, right?  And what do we use these for?  Is it running my ansible playbook to reset the HDDs?  That wouldn't work on linode anyway.  

So two AIs:

- conditionalize use of perf-dept playbook for RH-internal servers (i.e. hostname contains redhat.com)

- long-term - harden all our scripts to return a failure status if an error occurs

Cloning into 'perf-dept'...
fatal: unable to access 'http://git.app.eng.bos.redhat.com/git/perf-dept.git/': Could not resolve host: git.app.eng.bos.redhat.com; Unknown error
/root/automated_ceph_test/setup.sh: line 71: cd: perf-dept/sysadmin/Ansible: No such file or directory
/root/automated_ceph_test/setup.sh: line 74: ansible-playbook: command not found

**Comment by acalhounRH** [comment]
Updated code to install using coprs only. Marking closing/resolved. please open seperate issue for scripts/jobs that need to be hardened.
