### ISSUE TITLE
Prepare_Agent job isn't case-insensitive

### ISSUE THREAD

**Issue by bengland2** [acalhounRH/automated_ceph_test#4]
We probably want to make agent names be handled in a purely case-insensitive way or purely case-sensitive way.  Otherwise you wind up with master ~jenkins/agent_list like this one:

```
bash-4.4$ cat agent_list
bene_linode_jenkins_agent=li136-116.members.linode.com
Alex_Jenkins_Linode_Agent=li1032-230.members.linode.com
Bene_Linode_Jenkins_Agent=li1929-135.members.linode.com
```
And the other scripts only pick up the first match, I guess, because it failed to find the right IP address for my agent, which was Bene_Linode_Jenkins_Agent=li1929-135.members.linode.com.

**Comment by acalhounRH** [comment]
Fixed
